// Generated by CoffeeScript 1.10.0
var gacha, main;

main = function() {};

window.addEventListener("load", main);

gacha = function() {
  var cont, cont_id, cont_name, i, len, pro, rd, ref, url;
  rd = Math.floor(Math.random() * window.problems.length);
  pro = problems[rd];
  url = "http://" + pro.contest + ".contest.atcoder.jp/tasks/" + pro.id;
  cont_id = pro.contest;
  cont_name = "";
  ref = window.contests;
  for (i = 0, len = ref.length; i < len; i++) {
    cont = ref[i];
    if (cont.id === cont_id) {
      cont_name = cont.name;
      break;
    }
  }
  return $("#result").html("<a href=\"" + url + "\" target=\"_blank\">" + cont_name + "「" + pro.name + "」(" + pro.solvers + " solved)</a>");
};
